image: maven:3.6.1

pipelines:
  default:
    - step:
        name: Query Product
        caches:
          - maven
        script:
          - cd QueryProduct
          - mvn -B clean install
    - step:
        name: Command Product
        caches:
          - maven
        script:
          - cd CommandQuery
          - mvn -B clean install
    - step:
          name: Review Query
          caches:
            - maven
          script:
            - cd ReviewQuery
            - mvn -B clean install
    - step:
        name: Review Command
        caches:
          - maven
        script:
          - cd ReviewCommand
          - mvn -B clean install