image: maven:3.8.4-openjdk-8

pipelines:
  default:
    - step:
        name: AMQP
        caches:
          - maven
        script:
          - cd acme/amqp
          - mvn -B clean install
    - step:
        name: APIGW
        caches:
          - maven
        script:
          - cd acme/apigw
          - mvn -B clean install
    - step:
        name: Eureka
        caches:
          - maven
        script:
          - cd acme/eureka-server
          - mvn -B clean install
    - step:
        name: Query Product
        caches:
          - maven
        script:
          - cd acme/QueryProduct
          - mvn -B clean install
    - step:
        name: Command Product
        caches:
          - maven
        script:
          - cd acme/CommandProduct
          - mvn -B clean install
    - step:
          name: Review Query
          caches:
            - maven
          script:
            - cd acme/ReviewQuery
            - mvn -B clean install
    - step:
        name: Review Command
        caches:
          - maven
        script:
          - cd acme/ReviewCommand
          - mvn -B clean install