public class Cmyhwh {
    public static void main() {
        System.out.println("cmrmd");
        System.out.println("fffmy");
        System.out.println("mdwde");
        System.out.println("gxdis");
        System.out.println("xyyjo");
        System.out.println("uywoc");
        System.out.println("kqutu");
        System.out.println("frjut");
        System.out.println("ovmja");
        System.out.println("emijo");
        System.out.println("krdfg");
        System.out.println("fdhva");
        System.out.println("kedkj");
        System.out.println("refqm");
        System.out.println("rqmqt");
        System.out.println("mdmxx");
        System.out.println("xghkb");
        System.out.println("gaekr");
        System.out.println("invjd");
        System.out.println("kchsj");
        System.out.println("pcawu");
        System.out.println("rphxs");
        System.out.println("yjahv");
        System.out.println("jucht");
        System.out.println("keajr");
        System.out.println("hyfjq");
        System.out.println("hxefi");
        System.out.println("pxuyb");
        System.out.println("yaers");
        System.out.println("mhrby");
        System.out.println("xswlq");
    }
}
