server:
  port: 8087

spring:
  application:
    name: productCommand
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5672
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/command_product
      database: command_product

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

sku:
  interface:
    generator:
      default: skuA

database:
  interface:
    default: mongoDB

rabbitmq:
  exchanges:

  queues:
    product: product.queue

  routing-keys:
