server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: productCommandRoute
          uri: lb://PRODUCTCOMMAND
          predicates:
            - Path=/api/v1/product/**
            - Method=POST,PUT,DELETE
        - id: productQueryRoute
          uri: lb://PRODUCTQUERY
          predicates:
            - Path=/api/v1/product/**
            - Method=GET
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true