server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: productCommandRoute
          uri: lb://PRODUCTCOMMAND
          predicates:
            - Path=/api/v1/product/**
            - Method=POST,PUT,DELETE,PATCH
        - id: productQueryRoute
          uri: lb://PRODUCTQUERY
          predicates:
            - Path=/api/v1/product/**
            - Method=GET
        - id: reviewCommandRoute
          uri: lb://REVIEWCOMMAND
          predicates:
            - Path=/api/v1/reviews/**
            - Method=POST,PUT,DELETE
        - id: reviewQueryRoute
          uri: lb://REVIEWQUERY
          predicates:
            - Path=/api/v1/reviews/**
            - Method=GET
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true