server:
  port: 8086

spring:
  application:
    name: user
  rabbitmq:
    addresses: localhost:5672
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/user
      database: user
sku:
  interface:
    generator:
      default: skuA
user:
  interface:
    default: mongoDB1
database:
  interface:
    default: mongoDB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    product: product.queue
    product2: product2.queue
  routing-keys:
    internal-product: internal.product.routing-key

#Generator SKU

#Data Base


#Reviews
recommendation:
  alg: reviewA

